# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.2
      compiler: ": #GHC 7.10.2"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      compiler: ": #GHC head"
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
    - env: EVM_EMACS=emacs-24.5-travis
      compiler: "emacs-24.5"
    - env: EVM_EMACS=emacs-25.2-travis
      compiler: "emacs-25.2"
    - env: EVM_EMACS=emacs-git-snapshot-travis
      compiler: "emacs-git-snapshot"

  allow_failures:
    - env: CABALVER=head GHCVER=head
    - env: EVM_EMACS=emacs-git-snapshot-travis

before_install:
 - unset CC
 - if [ -n "${CABALVER:+1}" ];
   then
     export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH;
   fi

 - if [ -n "${EVM_EMACS:+1}" ];
   then
        ./travis-scripts/before_install-emacs.sh;
   fi

install:
  - if [ -n "${CABALVER:+1}" ];
    then
        ./travis-scripts/install-haskell.sh;
    fi

  - if [ -n "${EVM_EMACS:+1}" ];
    then
        ./travis-scripts/install-emacs.sh;
    fi

script:
  - if [ -n "${CABALVER:+1}" ];
    then
        ./travis-scripts/script-haskell.sh;
    fi

  - if [ -n "${EVM_EMACS:+1}" ];
    then
        cd elisp && cask build 2>&1 >/dev/null | grep "Error" | wc -l | grep "0";
    fi
